// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharesAPI.DatabaseAccess;

namespace SharesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200116231254_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SharesAPI.Models.AquiredShares", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("username");

                    b.ToTable("AquiredShares");
                });

            modelBuilder.Entity("SharesAPI.Models.Share", b =>
                {
                    b.Property<string>("symbol")
                        .HasColumnType("TEXT");

                    b.Property<int>("availableShares")
                        .HasColumnType("INTEGER");

                    b.Property<string>("currency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.Property<string>("shares")
                        .HasColumnType("TEXT");

                    b.HasKey("symbol");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("SharesAPI.Models.User", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<double>("pennies")
                        .HasColumnType("REAL");

                    b.HasKey("username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SharesAPI.Models.AquiredShares", b =>
                {
                    b.HasOne("SharesAPI.Models.User", null)
                        .WithMany("AquiredShares")
                        .HasForeignKey("username");
                });
#pragma warning restore 612, 618
        }
    }
}
